### ISSUE TITLE
implement final a11y work 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#455]
* [x] [Confirm which current PRs need merging](https://github.com/18F/pulse/issues/456)
* [x] Merge them
* [x] Update staging with ^^^^, while not updating production 
* [x] Engage OGP to re-scan site for a11y issues
* [ ] Kick off distinct thread on outstanding a11y issues 
* [ ] [Remove certain scripts from the pa11y scan test](https://github.com/18F/pulse/issues/453)
* [ ] Re-run the pa11y scan
* [ ] Update site with new data 
* [ ] Address total/average error language
* [ ] Try to address [adding in the 508 links](https://github.com/18F/pulse/issues/457)
* [ ] Affirm initial scan workflow and schedule

**Comment by gbinal** [comment]
This has been superseded by later events.
