### ISSUE TITLE
ATO status (for tracking purposes)

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#705]
Note - this issue is for convenience of team members outside of TTS, who cannot access the infrastructure.  The canonical issue for this project's ATO progress is [here](https://github.com/18F/Infrastructure/issues/708).  This issue will be updated periodically while that one will be the most up to date.  

---------------------

* **Main repository:** https://github.com/18f/pulse
* **Site:** https://pulse.cio.gov
* **Product manager:** @gbinal
* **System Owner:** @gbinal 
* **Infrastructure Lead:** @abisker 
* **ATO folder:** [link](https://drive.google.com/drive/u/1/folders/0B4f3E1-4As-aQUVOa21iZy02YWM)
* **Sprint notes:** [link](https://docs.google.com/a/gsa.gov/document/d/1HS2f4_qIbSqhXSmxi4WEys8ANRty4F25WJOaovFWK3c/edit?usp=sharing)

### Phase 1: ATO Sprint prerequisites

Everything in this section needs to be completed before the project will be scheduled for an ATO Sprint.

#### Infrastructure Lead

- [x] Set up an ATO intro meeting with the project team.
- [x] Determine the [impact level](https://pages.18f.gov/before-you-ship/ato/levels/) - Low (Open Data)
    * [x] Confirm with @NoahKunin 
- [x] Add this issue to the `Backlog` of [the ATO Kanban board](https://github.com/18F/Infrastructure/projects/1).
- [x] Assign the appropriate labels to this issue.
- [x] Set up the project ATO folder. - [link](https://drive.google.com/drive/u/1/folders/0B4f3E1-4As-aQUVOa21iZy02YWM)
    - [x] [In the `ATOs` folder in Google Drive](https://drive.google.com/a/gsa.gov/folderview?id=0BynIxtx-CfkdckljM3BPSkdQT1U&usp=sharing), go to `18F`/`OPP`/`PIF`, then `Work in progress`, and create a subfolder called in the format `<project> ATO - <duration> <level>`. Link to it as the `ATO folder` at the top of this issue.
    - [x] Add Rules of Engagement (RoE) template - [link](https://docs.google.com/document/d/1iwbRQPLEiqwON2GKpdSczlOSC2eBq2l60TVKaBq1sT0/edit)
        * Search [this page](https://insite.gsa.gov/portal/content/627238) for "Rules of Engagement (RoE) 90-Day LATO Penetration Test TEMPLATE", even if this isn't for a 90-day LATO.
    - [x] Add [System Security Plan (SSP)](https://pages.18f.gov/before-you-ship/ato/ssp/) template - [link](https://docs.google.com/document/d/1W2crmCdKLJYJu6qraJCDDdqXpf6YdDgj5YAD2iWAp1Q/edit)
        * For Low systems on cloud.gov, use [this template](https://docs.google.com/a/gsa.gov/document/d/1tVbH39TFfvSaBbjWfLaR3GLOuvsLuhLFJ75xKowEV5c/edit?usp=sharing)
    - [x] Add Project Plan template - [link](https://docs.google.com/document/d/1wReDjbcKhyTLYG4Y5PPQUXUiggVcOZk1GJ2fgLM9BBc/edit)
        * Search [this page](https://insite.gsa.gov/portal/content/627238) for "One Year LATO Project Plan Template", even if this isn't for a one-year LATO.
- [x] Make a copy of the [ATO Sprinting notes template](https://docs.google.com/document/d/1EdcNyE1kkQve3tHyiV1QIRWNOBlTeh33lAbX0h4h18M/edit) and save it in the [Sprinting Team folder](https://drive.google.com/open?id=1EdcNyE1kkQve3tHyiV1QIRWNOBlTeh33lAbX0h4h18M) with a title of `ATO Sprinting Team notes - <project>`. - [link](https://docs.google.com/document/d/1HS2f4_qIbSqhXSmxi4WEys8ANRty4F25WJOaovFWK3c/edit)
    - [x] Fill out the placeholders.
    - [x] Link to it as the `Sprint notes` at the top of this issue.

##### Technical

- [x] Enable [protected branches](https://help.github.com/articles/about-protected-branches/) for the project repositor(ies).
    * Get admin access via #admins-github, if needed.
- [x] Ensure that a staging environment is fully set up. - [link](https://staging.pulse.cio.gov)
    * This should be as [production](https://pages.18f.gov/before-you-ship/infrastructure/)-like as possible.
- [x] [Set up monitoring](https://pages.18f.gov/before-you-ship/infrastructure/monitoring/)
    * [x] [Downtime alerts](https://pages.18f.gov/before-you-ship/infrastructure/monitoring/#downtime)
    * [x] [Error & performance alerts](https://pages.18f.gov/before-you-ship/infrastructure/monitoring/#errors--performance-problems)
- [x] Perform security scans, and put the results (or a link to them) in the project's `ATO folder`.
    * [x] Set up [static analysis](https://pages.18f.gov/before-you-ship/security/static-analysis/) service
        * [x] Add service badges to the README
        * [x] Put a point-in-time PDF of the scan results in the project's `ATO folder`.
    * [x] [Perform dynamic vulnerability scanning](https://pages.18f.gov/before-you-ship/security/dynamic-scanning/)
        * [x] Resolve any visible security issues, re-running the scan as needed
        * [x] Add the issue-free scan report or [documentation about false positives](https://pages.18f.gov/before-you-ship/security/dynamic-scanning/#caveats) to the project's ATO folder.
- [x] If this is a new system, add a prominent [`Beta`](https://18f.gsa.gov/dashboard/stages/) label to the site.
- [x] Ensure the staging environment has sufficient capacity to withstand the testing.
    * The testing tools create very heavy usage and traffic.

##### Documentation

...reading and writing.

- [x] Read the LATO guide. - [link](https://docs.google.com/a/gsa.gov/document/d/14Xo8XQ4jueA7zhXRPb-Rw7pPRIWUeuxL-lQI_Ha6n_M/edit?usp=sharing)
    * Search [this page](https://insite.gsa.gov/portal/content/627230) for "Lightweight Security Authorization Process".
- [x] Create a [system diagram](https://pages.18f.gov/before-you-ship/ato/ssp/#systemnetwork-diagrams) - [link](https://docs.google.com/drawings/d/1ZwHY5gODuPTtLzdCdcrWBHxuHsMWFCkdmvr2InZAesE/edit)
- [ ] Fill out the Rules of Engagement (RoE) - [link](https://docs.google.com/document/d/1iwbRQPLEiqwON2GKpdSczlOSC2eBq2l60TVKaBq1sT0/edit)
    * Use staging URLs, rather than production ones.
- [ ] Fill out the Project Plan - [link](https://docs.google.com/document/d/1wReDjbcKhyTLYG4Y5PPQUXUiggVcOZk1GJ2fgLM9BBc/edit)
- [x] Add an [`.about.yml`](https://github.com/18F/about_yml) for the main repository - [link](https://github.com/18F/pulse/blob/master/.about.yml)
- [x] [Update relevant documentation](https://pages.18f.gov/before-you-ship/ato/tips/), primarily the README
- [x] Fill out the System Security Plan (SSP) - [link](https://docs.google.com/document/d/1W2crmCdKLJYJu6qraJCDDdqXpf6YdDgj5YAD2iWAp1Q/edit)
    * Work with your Infrastructure Lead on this.
    * Totally fine for this to be a rough first pass.
    * Your Infrastructure Lead will tell you if you should [do this via Compliance Masonry](https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications)

### Phase 2: Documentation review

1. [ ] Move this issue to the `Documentation review` column of [the ATO Kanban board](https://github.com/18F/Infrastructure/projects/1). - @[infrastructure lead]
1. [ ] Schedule a documentation review session. - @[infrastructure lead]
    * One or more follow-up sessions may be necessary.
1. [ ] Fix any documentation issues identified in the session.
1. [ ] RoE signed
    * [ ] System Owner
    * [ ] GSA IT

### Phase 3: ATO Sprint

1. [ ] Sprint started.
1. [ ] Polish up the System Security Plan (SSP).
1. [ ] Penetration test complete. - @[tester]
    * [ ] Enhanced Scanning and Assessment Process (ESAP) document added to ATO folder - @[tester]
1. [ ] Put all vulnerabilities from the ESAP in the project's issue tracker.
1. [ ] Fix any `Critical` or `High` vulnerabilities from the ESAP.
    * This needs to be done before the ATO can be issued, though not necessarily before the end of the sprint.

### Phase 4: Post-Sprint

1. [ ] Controls tested - @[GSA IT representative]
1. [ ] Create a Plan of Actions and Milestones (POAM). - @[GSA IT representative]
1. [ ] Final review and risk acceptance signatures (issue the ATO) - @[Authorizing Official]
1. [ ] Remove the `Beta` label from the site.
1. [ ] Fix all `Moderate` vulnerabilities - due [30 days after ATO issued]
1. [ ] Fix all `Low` vulnerabilities - due [60 days after ATO issued]

---

See the [Before You Ship](https://pages.18f.gov/before-you-ship/ato/) site for more information.

/cc @18F/ato

**Comment by afeld** [comment]
You can keep the checklist in just one place if you like. Having the issue in the Infrastructure repo specifically is more important for the labels and the placement in the kanban board.

**Comment by gbinal** [comment]
Sorry for the confusion, @afeld.  This is just for sharing with the site owner (who is outside of TTS and doesn't have access to the infrastructure repo).  

I'll update original issue to try and be more clear.

**Comment by afeld** [comment]
Makes sense! I'm saying: feel free to remove the checklist in the Infrastructure repo and just use this one.

**Comment by gbinal** [comment]
Ah.  Sorry, I see what you mean.  

Thank you that's kind.  I'm going to keep things as is though since I'm superstitious and messing with anything at all with this ATO.
